const mongoose = require('mongoose');
const Article = require('./Article');

const seededArticles = [
  {
    _id: '66c9f2b00000000000000001',
    title: 'How CRISPR Is Rewriting the Story of Human Disease',
    description: 'A quiet revolution in molecular biology has produced a tool precise enough to correct a single letter in the three-billion-character book of human DNA.',
    content: `The laboratory is a place of carefully managed uncertainty. For Priya Mehta, a morning at the bench begins not with pipettes and PCR machines, but with a kind of reckoning — with what might work, what might fail, and what could change everything.

CRISPR-Cas9, the gene-editing system that has dominated biology headlines since 2012, is now moving from bench to bedside with a speed that startles even its pioneers. In late 2023, the FDA approved the first CRISPR-based therapy for sickle cell disease, marking a turning point that scientists spent decades anticipating.

At its core, CRISPR relies on an ancient bacterial defense system. Bacteria use short repetitive RNA sequences coupled with Cas enzymes to recognize and destroy invading viral DNA. By repurposing this mechanism, researchers can direct Cas9 to any specific sequence in the human genome and execute precise double-stranded cuts.

The therapeutic implications are vast. Inherited blood disorders like beta-thalassemia and sickle cell anemia represent immediate clinical targets because hematopoietic stem cells can be extracted, edited ex vivo, and re-infused into patients. However, in vivo delivery—delivering CRISPR components directly into tissues like the liver, heart, or brain—remains the true frontier.`,
    category: 'Science',
    tags: ['biology', 'medicine', 'genetics', 'crispr'],
    status: 'published',
    heroImage: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=1200&q=80',
    views: 4821,
    likes: 284,
    readingTime: 7,
    author: {
      _id: '66c9f1a00000000000000003',
      id: '66c9f1a00000000000000003',
      name: 'Priya Mehta',
      email: 'priya.mehta@lumen.com',
      role: 'author',
      bio: 'Science communicator and molecular biologist. Writing about the invisible world.',
      avatar: '',
    },
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    _id: '66c9f2b00000000000000002',
    title: 'The Night the Internet Was Born — and Almost Wasn\'t',
    description: 'On October 29, 1969, a student typed two letters into a terminal at UCLA. The system crashed. The internet was born.',
    content: `At 10:30 PM on October 29, 1969, Charley Kline, a student programmer at UCLA, sat before a Teletype terminal connected to an SDS Sigma 7 mainframe. His goal was simple: transmit the word 'LOGIN' to a host computer at Stanford Research Institute, 350 miles to the north.

Kline typed 'L'. The terminal confirmed receipt over the phone line. He typed 'O'. Stanford received it. Then he typed 'G'. The system crashed.

Those two letters — 'LO' — became the first transmission on ARPANET, the precursor to today's global internet. What followed was fifty years of unprecedented technological integration, reshaping human communication, commerce, and culture.`,
    category: 'Technology',
    tags: ['history', 'computing', 'arpanet', 'internet'],
    status: 'published',
    heroImage: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1200&q=80',
    views: 3104,
    likes: 191,
    readingTime: 6,
    author: {
      _id: '66c9f1a00000000000000002',
      id: '66c9f1a00000000000000002',
      name: 'Thomas Okeke',
      email: 'author@lumen.com',
      role: 'author',
      bio: 'Historian of technology. Former editor at Nature. Coffee enthusiast.',
      avatar: '',
    },
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    _id: '66c9f2b00000000000000013',
    title: 'The Library of Alexandria and the Loss of Ancient Knowledge',
    description: 'Examining the papyrus scroll archives, classical scholarship, and the real historical causes behind the destruction of antiquity\'s greatest repository.',
    content: `For over six centuries, the Royal Library of Alexandria was the intellectual capital of the Mediterranean world. Founded under Ptolemy I Soter in the 3rd century BCE, its collection grew to over 400,000 papyrus scrolls spanning mathematics, astronomy, tragedy, and medicine.`,
    category: 'History',
    tags: ['History', 'Alexandria', 'Antiquity', 'Books'],
    status: 'published',
    heroImage: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?auto=format&fit=crop&w=1200&q=80',
    views: 4120,
    likes: 310,
    readingTime: 8,
    author: {
      _id: '66c9f1a00000000000000002',
      id: '66c9f1a00000000000000002',
      name: 'Thomas Okeke',
      email: 'author@lumen.com',
      role: 'author',
      bio: 'Historian of technology. Former editor at Nature. Coffee enthusiast.',
      avatar: '',
    },
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    _id: '66c9f2b00000000000000014',
    title: 'The Oceanic Carbon Pump: Deep-Sea Marine Ecosystems',
    description: 'Autonomous float arrays reveal how phytoplankton and deep-sea currents trap gigatons of carbon dioxide beneath the photic zone.',
    content: `Marine biological carbon pumps rely on micro-phytoplankton that absorb CO2 during photosynthesis and transport organic carbon to deep abyssal depths upon sinking.`,
    category: 'Environment',
    tags: ['Environment', 'Ocean', 'Carbon', 'Climate'],
    status: 'published',
    heroImage: 'https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=1200&q=80',
    views: 2650,
    likes: 198,
    readingTime: 6,
    author: {
      _id: '66c9f1a00000000000000003',
      id: '66c9f1a00000000000000003',
      name: 'Priya Mehta',
      email: 'priya.mehta@lumen.com',
      role: 'author',
      bio: 'Science communicator and molecular biologist. Writing about the invisible world.',
      avatar: '',
    },
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    _id: '66c9f2b00000000000000015',
    title: 'The Aesthetics of Minimalist Architecture in Modern Urban Spaces',
    description: 'How Scandinavian and Japanese design principles are reshaping public spaces, structural acoustics, and sustainable urban living.',
    content: `Modern urban architecture is embracing spatial efficiency, natural light integration, and natural material palettes to foster psychological well-being in dense urban environments.`,
    category: 'Other',
    tags: ['Architecture', 'Design', 'Urban', 'Other'],
    status: 'published',
    heroImage: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    views: 1890,
    likes: 142,
    readingTime: 5,
    author: {
      _id: '66c9f1a00000000000000002',
      id: '66c9f1a00000000000000002',
      name: 'Thomas Okeke',
      email: 'author@lumen.com',
      role: 'author',
      bio: 'Historian of technology. Former editor at Nature. Coffee enthusiast.',
      avatar: '',
    },
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    _id: '66c9f2b00000000000000016',
    title: 'Silk Road Trade Routes and Medieval Cultural Transmission',
    description: 'Mapping how paper-making, astronomy, optics, and mathematics traveled across Eurasian trade networks from Chang\'an to Baghdad.',
    content: `The Silk Road was far more than a commercial conduit for luxury textiles; it was an intellectual network where philosophical, astronomical, and medical treatises were translated across cultures.`,
    category: 'History',
    tags: ['History', 'SilkRoad', 'Culture', 'Eurasia'],
    status: 'published',
    heroImage: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=1200&q=80',
    views: 2980,
    likes: 215,
    readingTime: 9,
    author: {
      _id: '66c9f1a00000000000000002',
      id: '66c9f1a00000000000000002',
      name: 'Thomas Okeke',
      email: 'author@lumen.com',
      role: 'author',
      bio: 'Historian of technology. Former editor at Nature. Coffee enthusiast.',
      avatar: '',
    },
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    _id: '66c9f2b00000000000000017',
    title: 'Solar Photovoltaic Efficiency and Perovskite Tandem Cells',
    description: 'Breaking the Shockley-Queisser limit: How stacking silicon with synthetic perovskites pushes solar panel efficiency past 30 percent.',
    content: `Next-generation tandem solar cells combine silicon substrates with perovskite top layers to capture distinct solar spectrum wavelengths, achieving record laboratory efficiency.`,
    category: 'Environment',
    tags: ['Environment', 'Solar', 'CleanEnergy', 'Tech'],
    status: 'published',
    heroImage: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=1200&q=80',
    views: 3450,
    likes: 260,
    readingTime: 7,
    author: {
      _id: '66c9f1a00000000000000003',
      id: '66c9f1a00000000000000003',
      name: 'Priya Mehta',
      email: 'priya.mehta@lumen.com',
      role: 'author',
      bio: 'Science communicator and molecular biologist. Writing about the invisible world.',
      avatar: '',
    },
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    _id: '66c9f2b00000000000000007',
    title: 'Architectures of Deep Intelligence: Transformer Neural Networks Explained',
    description: 'How self-attention mechanisms and parallel matrix multiplication reshaped modern natural language processing and computer vision.',
    content: `In 2017, researchers at Google published "Attention Is All You Need", introducing the Transformer architecture. By discarding recurrent loops in favor of multi-head self-attention mechanisms, Transformers allowed sequence models to process entire text passages in parallel rather than token-by-token.`,
    category: 'Technology',
    tags: ['AI', 'Transformers', 'DeepLearning', 'Tech'],
    status: 'published',
    heroImage: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=1200&q=80',
    views: 5640,
    likes: 412,
    readingTime: 10,
    author: {
      _id: '66c9f1a00000000000000002',
      id: '66c9f1a00000000000000002',
      name: 'Thomas Okeke',
      email: 'author@lumen.com',
      role: 'author',
      bio: 'Historian of technology. Former editor at Nature. Coffee enthusiast.',
      avatar: '',
    },
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    _id: '66c9f2b00000000000000008',
    title: 'The Renaissance of Fusion Energy: Tokamaks and Inertial Confinement',
    description: 'Examining recent ignition breakthroughs at the National Ignition Facility and magnetic confinement plasma scaling.',
    content: `Nuclear fusion—the process that powers the sun—has long been hailed as the ultimate clean energy source. Recent experimental yields at NIF achieved net energy gain Q > 1.5, proving the physical viability of controlled fusion.`,
    category: 'Science',
    tags: ['Physics', 'Fusion', 'Energy', 'Science'],
    status: 'published',
    heroImage: 'https://images.unsplash.com/photo-1507413245164-6160d8298b31?auto=format&fit=crop&w=1200&q=80',
    views: 2890,
    likes: 230,
    readingTime: 8,
    author: {
      _id: '66c9f1a00000000000000003',
      id: '66c9f1a00000000000000003',
      name: 'Priya Mehta',
      email: 'priya.mehta@lumen.com',
      role: 'author',
      bio: 'Science communicator and molecular biologist. Writing about the invisible world.',
      avatar: '',
    },
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    _id: '66c9f2b00000000000000009',
    title: 'Macroeconomic Paradigms of Renewable Energy Markets',
    description: 'How falling levelized cost of electricity (LCOE) for solar and wind is reshaping global trade balances.',
    content: `Over the past decade, solar photovoltaic generation costs have plummeted by over 85%, making renewable generation cheaper than coal in over 80% of world markets. This transition alters international energy dependency.`,
    category: 'Business',
    tags: ['Business', 'Economics', 'Renewables'],
    status: 'published',
    heroImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
    views: 1980,
    likes: 154,
    readingTime: 6,
    author: {
      _id: '66c9f1a00000000000000002',
      id: '66c9f1a00000000000000002',
      name: 'Thomas Okeke',
      email: 'author@lumen.com',
      role: 'author',
      bio: 'Historian of technology. Former editor at Nature. Coffee enthusiast.',
      avatar: '',
    },
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    _id: '66c9f2b00000000000000010',
    title: 'Pedagogical Innovations in Open Access Digital Classrooms',
    description: 'Evaluating peer learning models, adaptive instruction algorithms, and global knowledge democratization.',
    content: `Digital education platforms are evolving from static video repositories to dynamic peer learning environments. Micro-credentials and automated mastery assessment enable personalized learning pathways.`,
    category: 'Education',
    tags: ['Education', 'Learning', 'Digital'],
    status: 'published',
    heroImage: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1200&q=80',
    views: 1430,
    likes: 98,
    readingTime: 5,
    author: {
      _id: '66c9f1a00000000000000003',
      id: '66c9f1a00000000000000003',
      name: 'Priya Mehta',
      email: 'priya.mehta@lumen.com',
      role: 'author',
      bio: 'Science communicator and molecular biologist. Writing about the invisible world.',
      avatar: '',
    },
    createdAt: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    _id: '66c9f2b00000000000000012',
    title: 'Neuroplasticity and Language Acquisition in Adulthood',
    description: 'Recent functional fMRI discoveries on adult synaptic adaptation during second-language immersion.',
    content: `It was long believed that the adult brain lost critical period malleability for natural language acquisition. Recent neuro-imaging studies show that intense immersive practice builds new white matter tracts in Broca's area.`,
    category: 'Health',
    tags: ['Neuroscience', 'Brain', 'Health', 'Language'],
    status: 'published',
    heroImage: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?auto=format&fit=crop&w=1200&q=80',
    views: 3210,
    likes: 275,
    readingTime: 7,
    author: {
      _id: '66c9f1a00000000000000003',
      id: '66c9f1a00000000000000003',
      name: 'Priya Mehta',
      email: 'priya.mehta@lumen.com',
      role: 'author',
      bio: 'Science communicator and molecular biologist. Writing about the invisible world.',
      avatar: '',
    },
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    _id: '66c9f2b00000000000000003',
    title: 'What the Ocean Is Trying to Tell Us About Carbon',
    description: 'Offshore monitoring arrays reveal that marine biological carbon pumps are sequestering CO2 at rates faster than previously modeled.',
    content: `Deep ocean carbon pumps rely on intricate marine ecosystem cycles where microscopic phytoplankton absorb carbon dioxide at the surface before sinking to the deep sea floor upon death. Recent autonomous float telemetry shows seasonal sequestration spikes.`,
    category: 'Environment',
    tags: ['ocean', 'climate', 'carbon', 'environment'],
    status: 'pending',
    heroImage: 'https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=1200&q=80',
    views: 340,
    likes: 28,
    readingTime: 3,
    author: {
      _id: '66c9f1a00000000000000003',
      id: '66c9f1a00000000000000003',
      name: 'Priya Mehta',
      email: 'priya.mehta@lumen.com',
      role: 'author',
      bio: 'Science communicator and molecular biologist. Writing about the invisible world.',
      avatar: '',
    },
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    _id: '66c9f2b00000000000000004',
    title: 'The Forgotten History of the Mechanical Computer',
    description: 'Long before silicon microchips, Victorian inventors built clockwork mechanical engines capable of calculating polynomial tables.',
    content: `Charles Babbage designed the Difference Engine and Analytical Engine in the 19th century, utilizing gear trains, punch cards, and mechanical columns to perform complex mathematical evaluations.`,
    category: 'Technology',
    tags: ['history', 'babbage', 'computing', 'mechanical'],
    status: 'changes_requested',
    reviewFeedback: 'Please expand section on ENIAC programmers and add inline citations.',
    heroImage: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=1200&q=80',
    views: 810,
    likes: 95,
    readingTime: 7,
    author: {
      _id: '66c9f1a00000000000000002',
      id: '66c9f1a00000000000000002',
      name: 'Thomas Okeke',
      email: 'author@lumen.com',
      role: 'author',
      bio: 'Historian of technology. Former editor at Nature. Coffee enthusiast.',
      avatar: '',
    },
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    _id: '66c9f2b00000000000000005',
    title: 'Sleep Debt and the Myth of the Weekend Recovery',
    description: 'New polysomnography trials demonstrate that sleeping in on Saturday cannot reverse chronic weekday micro-vascular inflammation.',
    content: `Chronic sleep restriction triggers systemic inflammatory markers that cannot be completely reset by compensatory sleep over the weekend. Neuro-cognitive resilience requires consistent circadian sleep schedules.`,
    category: 'Health',
    tags: ['sleep', 'health', 'neuroscience'],
    status: 'draft',
    heroImage: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=1200&q=80',
    views: 120,
    likes: 15,
    readingTime: 5,
    author: {
      _id: '66c9f1a00000000000000003',
      id: '66c9f1a00000000000000003',
      name: 'Priya Mehta',
      email: 'priya.mehta@lumen.com',
      role: 'author',
      bio: 'Science communicator and molecular biologist. Writing about the invisible world.',
      avatar: '',
    },
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
  {
    _id: '66c9f2b00000000000000006',
    title: 'Urban Forests and Micro-Climate Cooling',
    description: 'How dense canopy trees lower surface temperatures in urban heat islands.',
    content: `Tree canopies mitigate urban heat island effects through shade provision and evapotranspiration. High spatial resolution infrared thermography confirms canopy cooling offsets asphalt radiation.`,
    category: 'Environment',
    tags: ['urban', 'forests', 'climate'],
    status: 'rejected',
    reviewFeedback: 'Does not meet editorial scientific evidence standards.',
    heroImage: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=80',
    views: 65,
    likes: 8,
    readingTime: 4,
    author: {
      _id: '66c9f1a00000000000000003',
      id: '66c9f1a00000000000000003',
      name: 'Priya Mehta',
      email: 'priya.mehta@lumen.com',
      role: 'author',
      bio: 'Science communicator and molecular biologist. Writing about the invisible world.',
      avatar: '',
    },
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
  },
];

let inMemoryArticles = [...seededArticles];

module.exports = {
  seededArticles,
  inMemoryArticles,
};
